### ISSUE TITLE
Make file tree sorting case insensitive

### ISSUE THREAD

**Issue by TheLightBringer1991** [wiremod/advdupe2#298] opened 2020-07-02 10:50 UTC
![20200702124709_1](https://user-images.githubusercontent.com/40478437/86350126-8442ab00-bc62-11ea-8a56-eeabcf7fa44d.jpg)

As you can see from the screenshot, the order is not right 45 comes before 6.

**Comment by Divran** [comment] 2020-07-02 11:00
It's sorted alphabetically, so that is correct. You would have to name it
"06" to sort before "45"

**Comment by TheLightBringer1991** [comment] 2020-07-02 11:06
Windows sorts them right without the need to do that, isn't it possible to do the same?

**Comment by bigdogmat** [comment] 2020-07-02 18:07
Duplicate of #227 but that's closed so this works.

> Windows sorts them right without the need to do that, isn't it possible to do the same?

As said on the previous issue that's possible but not strictly alphabetically sorting.

**Comment by thegrb93** [comment] 2020-07-02 21:31
People who are used to the current ordering will run into the same confusion except in the opposite case. Its happened to me a few times jumping between Linux and Windows. Linux does pure ascii sorting while windows does its number parsing. I don't think this feature is good.

I would however like to see case insensitive sorting.

**Comment by thegrb93** [comment] 2020-08-21 02:00
I think just this needs to be updated https://github.com/wiremod/advdupe2/blob/605e86b413751470d67d64d4c12aec26ca570e66/lua/advdupe2/file_browser.lua#L736-L737

**Comment by thegrb93** [comment] 2020-11-30 23:50
Going to replace all table.sort with

```lua
local function tableSortNoCase(tbl)
    local sorted = {}
	for k, v in pairs(tbl) do sorted[#sorted+1] = {string.lower(v), v} end
	table.sort(sorted, function(a,b) return a[1]<b[1] end)
	for k, v in pairs(sorted) do tbl[k] = v[2] end
end
```

**Closed** 2020-12-03 02:47 UTC
Labels: enhancement
