### ISSUE TITLE
Map save functionality dupes don't save right

### ISSUE THREAD

**Issue by Fennecai** [wiremod/advdupe2#344] opened 2021-01-01 16:56 UTC
i save the map under the name ``mapsave`` and make sure that the ``advdupe2_MapFileName`` or whatever is also set to ``mapsave`` and ``advdupe2_loadmap`` is set to 1. but the saved map doesn't load.

i tried manually copying the saved map in the data folder to a sub-folder named the same as the actual map. in ``data/advdupe2_maps/`` still didn't work.

i tried renaming the file to the same as the map, and updating the convars accordingly.

still doesn't load anything in when i connect to the same map again.

pretty sure its broken.

**Comment by thegrb93** [comment] 2021-01-01 20:56
The file goes in data/advdupe2_maps

**Comment by Fennecai** [comment] 2021-01-02 01:51
thats where it already was; srry, wasnt clear on that

**Comment by Fennecai** [comment] 2021-01-02 01:53
the addon saves there by default anyways.

**Comment by thegrb93** [comment] 2021-01-12 21:33
It definitely does work, my server uses it. It's just a matter of getting it set up right.

**Comment by thegrb93** [comment] 2021-01-12 21:35
AdvDupe2_LoadMap 1
AdvDupe2_MapFileName <the file to load without .txt>

**Comment by thegrb93** [comment] 2021-01-12 21:35
`local filename = GetConVarString("AdvDupe2_MapFileName")`
`local map = file.Read("advdupe2_maps/"..filename..".txt")`

**Comment by thegrb93** [comment] 2021-01-12 21:35
https://github.com/wiremod/advdupe2/blob/master/lua/autorun/server/advdupe2_sv_init.lua#L63

**Comment by Fennecai** [comment] 2021-01-13 01:52
thats all what i did though and it doesn't work for me. is this a multiplayer server only thing?

**Comment by thegrb93** [comment] 2021-01-13 02:18
You should see Advdupe2 messages in console if it fails and AdvDupe2_LoadMap 1.

**Comment by Fennecai** [comment] 2021-01-13 02:30
i found something: 
``Missing HeadEnt index from Entities table[AdvDupe2Notify]	Could not open map save Missing HeadEnt index from Entities table
``

**Comment by thegrb93** [comment] 2021-01-13 03:34
Seems that save file is corrupt

**Comment by Fennecai** [comment] 2021-01-13 03:49
yep... it corrupts the save file no matter what i do. the save file is _always_ corrupt. i don't think it saves properly in the first place

**Comment by thegrb93** [comment] 2021-01-13 04:20
can you make sure you're up to date and if so, give some steps on how you're corrupting it.

**Comment by Fennecai** [comment] 2021-01-13 05:13
i am up-to-date.

how its getting corrupt:

1. load a map
2. spawn something
3. go into the adv dupe tool, open the map save section
4. type something like ``mapsave`` and hit ENTER...an error will happen probably.
5. manually click the little save icon to the right of the text box, now it will say the map was saved sucessfully
6. it obviously wasnt

**Comment by thegrb93** [comment] 2021-01-13 05:15
Try saving normally and just moving the file to the map folder.

**Comment by thegrb93** [comment] 2021-01-13 05:15
Also try loading that saved file normally

**Comment by Fennecai** [comment] 2021-01-13 05:18
loading and saving normal dupes works fine; ill tell you what it does for moving said dupes into the maps folder soon

**Comment by Fennecai** [comment] 2021-01-13 05:31
ok, I tested it now: loading a dupe as a save by moving it into the maps folder works perfectly; other than a huge lag spike that happens, but that's a minor inconvenience. 

its a bigger problem when i have to basically weld everything in the map together or something in order to ensure it saves properly with this method (cause if things arent welded they wont be considered part of the save, by design.)

so if you can figure out why the map save and normal dupe saving arent the same, that would be nice. ^^
especially since saving everything on a map makes gmod more fun by giving things more permanence.

**Comment by thegrb93** [comment] 2021-01-13 05:32
You don't need to weld everything. Just right click the world to copy everything. Can look into the map saving issue.

**Comment by Fennecai** [comment] 2021-01-13 05:34
ah ok, great. thanks.

**Comment by thegrb93** [comment] 2021-01-13 19:59
I don't see anything that could be causing the issue by looking at the code, so I'll have to test it out later.

**Comment by thegrb93** [comment] 2021-01-14 17:15
@Fennecai couldn't reproduce the issue but I think that error usually occurs if the duplicator tries to save something it cant. Do you know more detailed steps how to make it happen?

**Comment by Fennecai** [comment] 2021-01-14 18:58
nope. i dont understand it. i test by literally just spawning a blue barrel and saving that. :P

but if the saving code is supposed to function the same for both dupes and maps, then maybe refactor it to be identical in both places if its any different at all, and test if that works

**Comment by thegrb93** [comment] 2021-01-14 19:05
What map?

**Comment by Fennecai** [comment] 2021-01-15 00:53
gm_excess_island, gm_aquablocks, and i think gm_excess_construct_13 are all maps I've tried it on. 

it doesn't seem to be map dependant tbh; though its worth noting that saving map-wide dupes seems to copy map entities like built-in doors and stuff into said dupe, and a lot of my favorite maps have stuff like that.

**Comment by thegrb93** [comment] 2021-01-15 00:57
Yeah, it might be trying to save stuff it shouldn't. I'll check that.

**Comment by Fennecai** [comment] 2021-01-15 01:06
probably. i know in gm_excess_consrtuct_13, theres like a few combine buttons and a tv camera in one room that the duplicater picks up and tries to save, even in just a normal dupe thats not a map dupe.  I've been able to duplicate those entities with this.. not good. :P

**Comment by thegrb93** [comment] 2021-01-16 07:21
@Fennecai try this version. Should work https://github.com/thegrb93/advdupe2/archive/table-count-refactor.zip

**Comment by Fennecai** [comment] 2021-01-16 20:24
pressing enter in the save name box now works correctly; however, loading the save still doesnt work. i still get this error when i do an admin cleanup or reload the map:
``Missing HeadEnt index from Entities table[AdvDupe2Notify]	Could not open map save Missing HeadEnt index from Entities table
``

**Comment by thegrb93** [comment] 2021-01-16 20:52
Are you subscribed to the workshop version? That would overwrite the one i linked. I'll try some maps soon.

**Comment by Fennecai** [comment] 2021-01-17 08:55
i am not subbed to the workshop version.

**Comment by thegrb93** [comment] 2021-01-23 01:33
Ok, it's fixed now. Looks like the timed autocopy had the same issue but its fixed now too.

**Closed** 2021-01-23 01:36 UTC
Labels: bug

**Comment by Fennecai** [comment] 2021-01-23 02:56
alright- awsome. thanks
