### ISSUE TITLE
Adv Duplicator 2 crashes on prop_effect saving

### ISSUE THREAD

**Issue by UAVXP** [wiremod/advdupe2#88] opened 2016-05-07 17:51 UTC
If "Open file after Saving" unchecked:
addons/advdupe2/lua/advdupe2/sh_codec.lua:373: attempt to index upvalue 'buff' (a nil value)[AdvDupe2Notify]    File could not be decoded. Upload Canceled.

If checked:
addons/advdupe2/lua/advdupe2/sh_codec.lua:238: expected value, got EOF[AdvDupe2Notify]  DEBUG CHECK: File contains EOF errors.

**Comment by thegrb93** [comment] 2016-05-07 17:57
Can you describe the building?

**Comment by UAVXP** [comment] 2016-05-07 17:59
@thegrb93 Something like this
![20160507205906_1](https://cloud.githubusercontent.com/assets/3075683/15093654/967575be-1496-11e6-93dd-7c262232a93b.jpg)

**Comment by UAVXP** [comment] 2016-05-07 23:29
@thegrb93 Okay, just figured out why is this happening.
The problem was in dynamic entities (with effect circles on it) - that trees from props_foliage folder

**Comment by thegrb93** [comment] 2016-05-08 07:17
Those are prop_effect

**Comment by thegrb93** [comment] 2018-10-26 02:29
Might be fixed now, if not then https://github.com/wiremod/advdupe2/pull/138 may fix it. Otherwise, I can't reproduce it and need exact details of how to reproduce it.

**Closed by thegrb93** 2018-10-26 02:29 UTC
