### ISSUE TITLE
ALL Dupes "Invalid ghost parent" error

### ISSUE THREAD

**Issue by Ameno-Sagiri** [wiremod/advdupe2#182] opened 2018-12-20 08:45 UTC
When I attempt to load any dupe I have, it starts to generate the ghost, then errors out with "Invalid ghost parent." in a word bubble. I can still spawn my dupes, but I can no longer see ghosts for them. This is on the newest adv dupe 2 from github.

Here's the console when it happens:

```
[ERROR] addons/adv_dup2/lua/weapons/gmod_tool/stools/advdupe2.lua:1766: Tried to use a NULL entity!
  1. GetAngles - [C]:-1
   2. MakeGhostsFromTable - addons/adv_dup2/lua/weapons/gmod_tool/stools/advdupe2.lua:1766
    3. fn - addons/adv_dup2/lua/weapons/gmod_tool/stools/advdupe2.lua:1799
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

[AdvDupe2Notify]	Invalid ghost parent.

```

I see it's mentioning ulib/ulx, wondering if something there is interfering maybe?

**Comment by thegrb93** [comment] 2018-12-21 19:32
We didn't change anything related to ghosts.

Going to need the dupe to reproduce it.

**Comment by thegrb93** [comment] 2018-12-29 22:04
Also ulx isn't the cause, but I think a 3rd party mod may be at fault.

**Comment by thegrb93** [comment] 2019-01-21 17:38
Closing since needed info isn't provided

**Closed by thegrb93** 2019-01-21 17:38 UTC
Labels: cant reproduce
