### ISSUE TITLE
sv_clipboard.lua:515: Tried to use invalid object (type IPhysicsObject)

### ISSUE THREAD

**Issue by thegrb93** [wiremod/advdupe2#38] opened 2015-02-03 11:50 UTC
After playing gmod for a while I'll get this error for all my dupes and needs a server restart to fix.
```
[AdvDupe2Notify]	addons/advdupe2/lua/advdupe2/sv_clipboard.lua:515: Tried to use invalid object (type IPhysicsObject) (Object was NULL or not of
```

**Comment by thegrb93** [comment] 2015-02-03 11:58
For some reason it becomes impossible to spawn props from the prop menu when this occurs too.

**Comment by AbigailBuccaneer** [comment] 2015-02-03 19:58
Is there no more error than that? It seems to be cut off, which means there's no stack trace to go with it :(

**Comment by thegrb93** [comment] 2015-02-03 23:54
Yeah the it showed the error as a hint which I guess has a maximum string length and it printed the same text to the console.

**Comment by thegrb93** [comment] 2015-02-03 23:56
I think there's something going wrong in garrysmod that makes props unable to spawn for whatever reason and the advdupe2 doesn't handle the invalid physics objects that remain from the unspawned entities.

**Comment by Grocel** [comment] 2015-07-22 19:34
Looks like a missing IsValid() check. I have problems with it too. For me it is caused by an addon I am developing. It has scripted entities that spawns other entities. These are removed on duplication to prevent them from spawning twice and being broken. However I'm not able to fix that in my addon.
It's working fine on ADV Dupe.

The Error for me is slightly different: "lua/advdupe2/sv_clipboard.lua:515: Tried to use a NULL physics object!"

If you need more information I will give you more.

**Comment by Grocel** [comment] 2015-08-09 02:23
@Nebual As this is fixed now, it can closed too. :)

**Closed** 2015-08-09 03:10 UTC
Labels: bug
