### ISSUE TITLE
Constraints lose all strenght if edited after being duped

### ISSUE THREAD

**Issue by TheLightBringer1991** [wiremod/advdupe2#194] opened 2019-01-11 20:31 UTC
Everytime I edit constraints on one of my builds (like a tank) and dupe it, the duped tank's constraints all sag; Ropes lose their firmness, ballsockets don't lock anymore and various more bugs.

**Comment by thegrb93** [comment] 2019-01-11 21:35
Try with the latest version. That issue was already addressed.

**Comment by thegrb93** [comment] 2019-01-11 21:36
Otherwise, I need the dupe so that I can verify the fix is working or not.

**Comment by TheLightBringer1991** [comment] 2019-01-12 01:55
Happens with latest version. I have a simple dupe here: 
https://garrysmods.org/download/59872/isu-152-oversized-130

Any change of the constraints messes it up.

**Comment by thegrb93** [comment] 2019-01-12 02:46
Ok I'll look

**Comment by thegrb93** [comment] 2019-01-12 03:31
Ok so there's over 200 constraints so 3 groups of the tank will be floppy. The max constraints per system is 100. Previous versions of advdupe2 kept the floppyness consistent but still occurred. with this version the floppyness will change depending on new constraints.

**Comment by thegrb93** [comment] 2019-01-12 03:32
One thing I can do is add the nocollides last since they add to the phys_constraintsystem but doesn't matter if they make a new one or not.

**Comment by TheLightBringer1991** [comment] 2019-01-12 03:35
Any other way to fix it? Tanks with suspensions are bound to be over the 100 limit.

**Comment by thegrb93** [comment] 2019-01-12 03:44
Try this https://github.com/wiremod/advdupe2/pull/195 copy that file and try and see if that helps.

**Comment by TheLightBringer1991** [comment] 2019-01-12 04:00
How do i copy it? I'm on the chrome version of github

**Comment by thegrb93** [comment] 2019-01-12 04:12
https://raw.githubusercontent.com/wiremod/advdupe2/c4aebd310c390ba4d27de54249f3f35e27628997/lua/weapons/gmod_tool/stools/advdupe2.lua

**Comment by TheLightBringer1991** [comment] 2019-01-12 04:15
oh, I just copy it manually. Thought I didn't see a download button or something.

**Comment by thegrb93** [comment] 2019-01-12 05:16
you can increase it but the game will crash

**Comment by thegrb93** [comment] 2019-01-12 05:40
can you give me a dupe of the one with modified constraints?

**Comment by TheLightBringer1991** [comment] 2019-01-12 05:42
My way of making suspension and all didn't change from that dupe, so it's the same 100%

**Comment by thegrb93** [comment] 2019-01-12 06:08
What's re-elastic? I tried moving the constrains and didn't see any wobbling. I did see the separation of constraint systems though which is unavoidable.

**Comment by thegrb93** [comment] 2019-01-12 06:15
If you can give me a dupe where the wobbling is obvious, maybe I can figure out a way to better it.

**Comment by TheWizardLizard** [comment] 2019-01-12 07:17
> What's re-elastic? I tried moving the constrains and didn't see any wobbling. I did see the separation of constraint systems though which is unavoidable.

Re-elastic allows you to recreate elastic constraints with new values, since unlike hydraulics they cannot be edited (without re-elastic) after they are created.

https://steamcommunity.com/sharedfiles/filedetails/?id=481216549

**Comment by TheLightBringer1991** [comment] 2019-01-12 08:40
If you just dupe it, it's fine. The problem arises when you edit a constraint or remove or add one, then you dupe the creation and spawn it. The spawned one is the bugged one. Try to take my tank fior example, remove the elastics and readd them, or just edit them with the re-elastic tool if you have it. The problem is very evident, like the whole gun flops around like a wet noodle or the wheels get all wobbly. It's nothing mid and hard to see.

**Comment by TheLightBringer1991** [comment] 2019-01-12 23:07
[test.zip](https://github.com/wiremod/advdupe2/files/2752629/test.zip)

**Comment by TheLightBringer1991** [comment] 2019-01-13 01:38
So there's no fix possible?

**Comment by thegrb93** [comment] 2019-01-13 02:31
Less constraints

**Comment by thegrb93** [comment] 2019-01-13 04:07
Let me look at the test you sent.

**Comment by thegrb93** [comment] 2019-01-13 07:33
Seems like the wobble is much worse in multiplayer than singleplayer or something, that's why I couldn't see it I guess.

**Comment by thegrb93** [comment] 2019-01-13 07:40
I got it wobbling once, but now i can't reproduce again. it's just the table ordering that causes the wobble to appear in some random place.

**Comment by thegrb93** [comment] 2019-01-13 07:42
And table ordering can be random with lua when table indices are in-sequential.

**Comment by thegrb93** [comment] 2019-01-13 07:46
Hm when I pasted it earlier it wobbled, but the later I pasted again and it didn't. I think the wire_latch is the issue since it puts a rogue constraint-system in before the dupe's constraints are even added.

**Comment by thegrb93** [comment] 2019-01-13 08:50
https://github.com/wiremod/wire/issues/1825

**Closed** 2019-01-13 08:50 UTC
Labels: Fix pending, bug

**Comment by thegrb93** [comment] 2019-01-14 01:06
@TheLightBringer1991 https://github.com/wiremod/wire/pull/1826 should fix the wire latch causing wobbling.

**Comment by TheLightBringer1991** [comment] 2019-01-14 03:36
would be better if latches spawned deactivated though, now they spawn all welded no matter what.
