### ISSUE TITLE
Advanced dupe saves stuck on "opening"

### ISSUE THREAD

**Issue by Jackywagon** [wiremod/advdupe2#165] opened 2018-12-01 19:08 UTC
Whenever I open a dupe I make it is stuck on "opening" and I cant open any other dupes and it says "adv dupe is busy". I can open dupes from a long time ago but if I save a new one now this problem happens. Adv dupe is unusable in this state and is impossible to open any new projects.
![opening](https://user-images.githubusercontent.com/45520516/49331991-456edf80-f56b-11e8-93d7-3dabe38d978c.JPG)

**Comment by thegrb93** [comment] 2018-12-01 19:49
Duplicate of https://github.com/wiremod/advdupe2/issues/164 and https://github.com/wiremod/advdupe2/issues/163

**Comment by thegrb93** [comment] 2018-12-01 21:19
Will leave open until the error handler is fixed

**Closed** 2018-12-03 03:39 UTC
Labels: Fix pending, duplicate
