### ISSUE TITLE
advanced duplicator 2 stuck at opening 

### ISSUE THREAD

**Issue by mashed1potato** [wiremod/advdupe2#223] opened 2019-04-19 15:16 UTC
![Screenshot (27)](https://user-images.githubusercontent.com/49789711/56430563-01386d80-62c7-11e9-896b-a76591245332.png)
i got a issue 2 months ago where i can't open dupes and it's stuck at the last part of loading it. my game will lag untill i reconect. this only happens on servers. i tryed to redownload the addon added the original advanced duplicater fille what should had fixed the problem (didn't), i re saved all my dupes i tryed to verify game files and i tryed to wait untill it would work. the server restarted a lot of times.

i have shecked a lot of post about this propblems and fixes but nothing worked. i really need it to work because the advanced duplicator is the reasosn why i'm still playing gmod.

i really need help and if there is a known fix the i haven't found than please help me. thanks in advanced.

**Comment by thegrb93** [comment] 2019-04-19 15:40
Need the file it's having a problem with, or you need to check the server console or error logs for lua errors.

**Comment by mashed1potato** [comment] 2019-04-19 15:45
it's with every fille. and this are the ting in console they are there 30+times
Error Vertex File for 'props\cs_office\Exit_wall.mdl' checksum 561535357 should be -1373013452
Error Vertex File for 'props\CS_Assault\Floodlight01.mdl' checksum -1689989087 should be -1647330311
Error Vertex File for 'props\de_Nuke\Floodlight.mdl' checksum 810312973 should be -697262290

**Comment by thegrb93** [comment] 2019-04-19 15:47
Server console, not client.

**Comment by thegrb93** [comment] 2019-04-19 15:47
It's most likely this one https://github.com/wiremod/advdupe2/issues/205

**Comment by thegrb93** [comment] 2019-04-19 15:48
https://github.com/wiremod/advdupe2/issues/164

**Comment by mashed1potato** [comment] 2019-04-19 15:49
i think not because only a hand full of poeple have the problem and the server i'm playing on is the biggest or on of the biggest in darkrp, so i think they have to latest update.

**Comment by mashed1potato** [comment] 2019-04-19 15:50
and i tryed the github advanced duplicator fille but it didn't work

**Comment by thegrb93** [comment] 2019-04-19 15:58
You tried it in singleplayer or on the server? It won't affect anything on the server. Doesn't matter how big the server is, it could be using old versions.

**Comment by mashed1potato** [comment] 2019-04-19 16:01
I did work in a private world

**Comment by thegrb93** [comment] 2019-04-19 16:01
Also yeah, only a handful of people having the problem sounds about right. If you saved a file using new version of advdupe and try to load it using old version, that's where the issue is.

**Comment by thegrb93** [comment] 2019-04-19 16:04
Try closing gmod, removing cfg/client.vdf and starting a singleplayer game again. If none of that works, you'll need to remove addons or reinstall gmod until it works because something is breaking things. It works fine for everyone else.

**Comment by thegrb93** [comment] 2019-04-19 16:05
Or put a dupe file here that I can try opening

**Comment by mashed1potato** [comment] 2019-04-19 16:15
[indus_tunnol_roof.txt](https://github.com/wiremod/advdupe2/files/3098660/indus_tunnol_roof.txt)
[crakhous_base.txt](https://github.com/wiremod/advdupe2/files/3098661/crakhous_base.txt)
[diamond.txt](https://github.com/wiremod/advdupe2/files/3098662/diamond.txt)

**Comment by mashed1potato** [comment] 2019-04-19 16:16
i closed it on exsidant

**Comment by thegrb93** [comment] 2019-04-19 16:31
I'll try when I get home from work

**Comment by mashed1potato** [comment] 2019-04-19 16:54
[port_1.txt](https://github.com/wiremod/advdupe2/files/3098764/port_1.txt)

this one to this one is welded togeter so it might be different

**Comment by mashed1potato** [comment] 2019-04-20 00:42
I'm thinking it might be a problem with weld. I have something saved that isn't welded together and I can spawn that in with no propblems.

**Comment by thegrb93** [comment] 2019-04-20 05:40
They load fine for me so it's probably an addon you have breaking it

**Comment by mashed1potato** [comment] 2019-04-20 08:57
I will delete every addon in my game folder then

**Comment by mashed1potato** [comment] 2019-04-20 10:40
removed all addons except advanced duplicator and still doesn't work on the server

**Comment by thegrb93** [comment] 2019-04-20 22:21
Removing your addons won't change what's broken on the server. The point of removing all your addons is to make it work in singleplayer.

**Comment by thegrb93** [comment] 2019-04-20 22:22
If it works in singleplayer and not the server, then its the server's issue. Probably using outdated advdupe2.

**Closed** 2019-04-24 21:55 UTC
