### ISSUE TITLE
Pasting a creation which has many colored props usually pastes some of the areas without colors.

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/advdupe2#142] opened 2018-08-28 13:24 UTC
Apparently, me and a friend created a prop drawing using many small PHX cubes, and attempted to save it. But pasting it seems to remove a part of the colors.

**Comment by thegrb93** [comment] 2018-08-28 23:16
Couldn't reproduce. How did you color the entities and can i have a copy of the dupe?

**Comment by thegrb93** [comment] 2018-10-26 02:56
Probably due to using e2 to color some of the props. That should be fixed now though

**Closed** 2018-10-26 02:55 UTC
Labels: need info
