### ISSUE TITLE
Spawners of composite props become faulty after being duplicated themselves

### ISSUE THREAD

**Issue by Seedmanc** [wiremod/advdupe2#44] opened 2015-02-23 10:40 UTC
When you make a spawner out of two or more props welded together and then duplicate the resulting spawner itself, very often it will be duplicated with offsets between ghosts of welded props. This applies to props produced from this duplicated spawner, they're all offset and that results in them flying at great speed somewhere at the moment of spawning. In rare cases that doesn't happen and the duplicated spawner works, but it seems to be random. Moreover, attaching the spawner to some contraption before duplication of the entire thing seems to guarantee incorrect behaviour for sure.

All this means it would be impossible to save and load contraptions with composite prop spawners in them. No custom multipart rocket launchers and whatnot.

**Comment by Jack37** [comment] 2015-02-23 18:25
Duplicate of #23

**Comment by Seedmanc** [comment] 2015-02-23 19:45
Not sure how this is duplicate. I didn't quite understand what the #23 was talking about, was he suggesting one-time use self-removing spawners?  Seems different and I don't see much use of that anyway.

**Comment by Seedmanc** [comment] 2015-03-21 16:00
pls explain

**Comment by Jack37** [comment] 2015-03-21 17:35
He is referring to the same problem in the first part of his issue, it's just not explained very well. I didn't understand what did he mean either, until I tested it in game.

**Comment by thegrb93** [comment] 2018-10-26 00:34
Must've been fixed a long time ago. Duping contraption spawners seems to be fine.

**Comment by thegrb93** [comment] 2018-10-26 00:36
Nevermind, I see it now.

**Closed** 2018-10-27 16:58 UTC
Labels: Fix pending, bug
