### ISSUE TITLE
Open file while opening file lockup

### ISSUE THREAD

**Issue by TheFreezebug** [wiremod/advdupe2#53] opened 2015-08-10 22:59 UTC
Opening a file while opening a file will warn you that advance duplicator 2 is already opening a file, but it will not allow you to open a file whilst in that session any more, you need to rejoin.

**Comment by AbigailBuccaneer** [comment] 2015-08-31 12:13
Duplicate of #9.

**Closed by AbigailBuccaneer** 2015-08-31 12:13 UTC
