### ISSUE TITLE
Saving hangs for a long time and gives 'File contains EOF errors' message

### ISSUE THREAD

**Issue by pumab9** [wiremod/advdupe2#106] opened 2016-12-13 11:25 UTC
I'm trying to add advdup2 to my server, and the saving part is EXTRA slow, like takes like 5min to save 1 prop, and then it gives this error:

addons/advanced_duplicator_2_773402917/lua/advdupe2/sh_codec.lua:366: File could not be decompressed.[AdvDupe2Notify]DEBUG CHECK: File contains EOF errors.

I tried to add the github version and the workshop version too, I also tried to delete it from data folder before reinstalling. I have even tried to remove my sv.db file and try it like that.
thanks for the help!

**Comment by pumab9** [comment] 2017-01-02 21:25
Forgot to mention server is running on linux

**Comment by oldmud0** [comment] 2017-01-03 06:16
Is the filesystem mounted with any extra options? e.g. writeback, barriers, etc?

**Comment by pumab** [comment] 2017-01-03 17:09
Nope, it's as default as it can be, no restrictions of any sort

**Comment by TBbadmofo** [comment] 2017-01-14 08:45
User's AdvDupe2_MaxDownloadBytes2 convar was set to 0 which resulted in a never ending network transfer of zero data until network timeout.

**Comment by thegrb93** [comment] 2017-01-14 21:11
This has happened only once for me when I was trying to save something and I started removing SENTS on it until it saved correctly. Have to test some more to see what it was specifically, if I can even reproduce it.

**Comment by TBbadmofo** [comment] 2017-01-14 23:41
It modified your convars?
An EOF error can happen for any number of reasons. It's the validation check after a file has been encoded and transferred to the player. So a SENT could have also messed up the encoding somehow and failed the validation.  In this case though, he had his server transfer rate for AD2 set to 0 so it never sent any data for the player to validate.

**Comment by pumab** [comment] 2017-01-15 12:26
Thank you so much for solving this :)

**Comment by thegrb93** [comment] 2018-10-26 02:38
Should be fixed by https://github.com/wiremod/advdupe2/pull/138 there were rare cases of corruption in the current codec

**Closed by thegrb93** 2018-10-26 02:38 UTC
Labels: bug
